# Service definitions for Aurora Sound to Light

security_audit:
  name: Security Audit
  description: Perform a security audit and return findings about the system's security status.

reset_rate_limits:
  name: Reset Rate Limits
  description: Reset rate limiting counters for a specific client or all clients.
  fields:
    client_id:
      name: Client ID
      description: The ID of the client to reset. If not provided, resets all clients.
      required: false
      example: "192.168.1.100"
      selector:
        text:

unban_client:
  name: Unban Client
  description: Manually unban a client that has been temporarily banned due to excessive failed attempts.
  fields:
    client_id:
      name: Client ID
      description: The ID of the client to unban.
      required: true
      example: "192.168.1.100"
      selector:
        text:

get_audit_log:
  name: Get Audit Log
  description: Retrieve filtered security audit log entries.
  fields:
    start_time:
      name: Start Time
      description: Filter entries after this timestamp (ISO format).
      required: false
      example: "2023-12-18T00:00:00"
      selector:
        datetime:

    end_time:
      name: End Time
      description: Filter entries before this timestamp (ISO format).
      required: false
      example: "2023-12-18T23:59:59"
      selector:
        datetime:

    client_id:
      name: Client ID
      description: Filter entries for a specific client.
      required: false
      example: "192.168.1.100"
      selector:
        text:

    request_type:
      name: Request Type
      description: Filter entries by request type (e.g., "effect", "light_group", "security").
      required: false
      example: "effect"
      selector:
        select:
          options:
            - "effect"
            - "light_group"
            - "security"

    success:
      name: Success
      description: Filter entries by success status.
      required: false
      selector:
        boolean:

# ... existing services below ... 